name: stream_duration
description: A dart package for stream duration.
version: 1.1.0
homepage: https://github.com/farhanfadila1717/stream_duration

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
